apiVersion: apps/v1
kind: Deployment
metadata:
  name: vul-workload
spec:
  selector:
    matchLabels:
      app: vul-workload
  template:
    metadata:
      labels:
        app: vul-workload
    spec:
      containers:
      - image: REPO_ID:IMAGE_TAG
        name: vul-site
