apiVersion: apps/v1
kind: Deployment
metadata:
  name: vul-workload
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vul-workload
  template:
    metadata:
      labels:
        app: vul-workload
    spec:
      containers:
      - image: REPO_ID:IMAGE_TAG
        name: vul-site
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - vul-workload
            topologyKey: "kubernetes.io/hostname"
