apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vul-workload
  name: vul-workload
  namespace: default
spec:
  selector:
    matchLabels:
      app: vul-workload
    spec:
      containers:
      - image: gcr.io/my-rd-ce-horng-lee/REPO_ID:IMAGE_TAG
        imagePullPolicy: IfNotPresent
        name: vul-site
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
